name: automerge
on:
  pull_request:

jobs:

  automerge:
    name: Merge pull request
    runs-on: [ubuntu-latest]
#    needs: [build]
#    if: github.base_ref == 'master'
    steps:
      - name: Merge
        uses: actions/github-script@0.9.0
        with:
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{secrets.kalpana}}