name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:

  automerge:
    name: Merge pull request
    runs-on: [ubuntu-latest]
#    needs: [build]
    if: github.base_ref == 'master'
    steps:
      - name: Merge
        uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.kalpana}}
#
#  automerge:
#    runs-on: ubuntu-latest
#    steps:
#      - name: automerge
#        uses: "pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a"
#        env:
#          GITHUB_TOKEN: ${{ secrets.kalpana }}